### ISSUE TITLE
Why does the pretrained model predict all keypoints at the center of the image?

### ISSUE THREAD

**Issue by chaneyddtt** [ESanchezLozano/SAIC-Unsupervised-landmark-detection-NeurIPS2019#3]
Hi, 
Thanks for your awesome work. I find that that the pretrained model predicts all keypoints at the center of the image for the CelebA dataset. Do you have any idea on why this happens?

**Comment by ESanchezLozano** [comment]
Hi,

The pretrained model that can be found in the folder is the one that has been pre-trained on MPII (see paper Section 4.1). For CelebA you need to adapt the model using the provided code. The amount of parameters to be updated is fairly low and it should produce competitive results already after an hour approximately on a single GPU.

**Comment by chaneyddtt** [comment]
Ok, thanks a lot for your reply.
